#!/bin/bash

evsieve \
    --input /dev/input/wiimote3 domain=wiimote3 grab persist=exit \
        --map btn:south@wiimote3 btn:mode@wiitar3 \
        --map btn:1@wiimote3 btn:thumbl@wiitar3 \
        --map btn:2@wiimote3 btn:thumbr@wiitar3 \
        --map btn:mode@wiimote3 btn:z@wiitar3 \
        --map key:next@wiimote3 btn:start@wiitar3 \
        --map key:previous@wiimote3 btn:select@wiitar3 \
        --map key:left@wiimote3 btn:dpad_up@wiitar3 \
        --map key:right@wiimote3 btn:dpad_down@wiitar3 \
        --map key:up@wiimote3 btn:dpad_left@wiitar3 \
        --map key:down@wiimote3 btn:dpad_right@wiitar3 \
    --input /dev/input/wiiguitar3 domain=guitar3 grab persist=exit \
        --map btn:1@guitar3 btn:south@wiitar3 \
        --map btn:2@guitar3 btn:east@wiitar3 \
        --map btn:3@guitar3 btn:north@wiitar3 \
        --map btn:4@guitar3 btn:west@wiitar3 \
        --map btn:5@guitar3 btn:tl@wiitar3 \
        --map btn:start@guitar3 btn:start@wiitar3 \
        --map btn:select@guitar3 btn:select@wiitar3 \
        --map btn:dpad_up@guitar3 btn:dpad_up@wiitar3 \
        --map btn:dpad_down@guitar3 btn:dpad_down@wiitar3 \
        --map abs:hat1x@guitar3 abs:rx:3x@wiitar3 \
        --map abs:x@guitar3 abs:x@wiitar3 \
        --map abs:y@guitar3 abs:y@wiitar3 \
    --input /dev/input/wiiaccel3 domain=accel3 grab persist=exit \
        --block abs:rz@accel3 abs:rx@accel3 \
        --map abs:ry:-59~..~-60@accel3 btn:select:1@wiitar3 \
        --map abs:ry:~-60..-59~@accel3 btn:select:0@wiitar3 \
    --output name="Wiitar w/ Tilt 3" @wiitar3

