#!/bin/bash
# /userdata/roms/clonehero/wiitar-dev-namer script to provide a static name for wiitar controllers 
# Called by udev rule to create static device entries that link to the dynamically /dev/input/event<n>
# This  is useful when the device order changes but you need a static way to refer to the same device 
# I use this is retropie to create a static mapping for my ps3 controller events and joysticks
#
# To use this script create “/etc/udev/rules.d/99-wiitar.rules” with the following line
# less the leading ‘#” character
# ATTRS{name}=="", PROGRAM="/bin/device_namer %k", SYMLINK+="%c"
 
BASENAME="/dev/input/wiimote-guitar"	# Change if you have a different controller
COUNT=1
 
if [[ $1 == js* ]]			# if we have a js<n> device		
then
        TYPE="_js"			# Append “_js”
elif [[ $1 == event* ]]		# else if we have an event<n> device
then
        TYPE=""		# Append “_event”
fi
 
while [ $COUNT -le 100 ]                # Main loop with backup plan to exit after 100 trys. 
do
        NAME="$BASENAME$COUNT$TYPE"     # Build filename to test for
 
        if [ -e $NAME ]                 	# if the file exists
        then
                ((COUNT+=1))            	# increment count and try the next possible entry
        else                            		# file does not exist
                echo $NAME | cut -c 6-  # output the name of the first available link less the "\dev" prefix
                break                   	# break the loop and exit
        fi
done
