#!/bin/bash
for i in {1..4}; do
    evsieve \
        --input /dev/input/wiimote$i domain=wiimote$i grab persist=exit \
            --map btn:south@wiimote$i btn:mode@wiitar$i \
            --map btn:1@wiimote$i btn:thumbl@wiitar$i \
            --map btn:2@wiimote$i btn:thumbr@wiitar$i \
            --map btn:mode@wiimote$i btn:z@wiitar$i \
            --map key:next@wiimote$i btn:start@wiitar$i \
            --map key:previous@wiimote$i btn:select@wiitar$i \
            --map key:left@wiimote$i btn:dpad_up@wiitar$i \
            --map key:right@wiimote$i btn:dpad_down@wiitar$i \
            --map key:up@wiimote$i btn:dpad_left@wiitar$i \
            --map key:down@wiimote$i btn:dpad_right@wiitar$i \
        --input /dev/input/wiimote-guitar$i domain=guitar$i grab persist=exit \
            --map btn:1@guitar$i btn:south@wiitar$i \
            --map btn:2@guitar$i btn:east@wiitar$i \
            --map btn:3@guitar$i btn:north@wiitar$i \
            --map btn:4@guitar$i btn:west@wiitar$i \
            --map btn:5@guitar$i btn:tl@wiitar$i \
            --map btn:start@guitar$i btn:start@wiitar$i \
            --map btn:select@guitar$i btn:select@wiitar$i \
            --map btn:dpad_up@guitar$i btn:dpad_up@wiitar$i \
            --map btn:dpad_down@guitar$i btn:dpad_down@wiitar$i \
            --map abs:hat1x@guitar$i abs:rx:3x@wiitar$i \
            --map abs:x@guitar$i abs:x@wiitar$i \
            --map abs:y@guitar$i abs:y@wiitar$i \
        --input /dev/input/wiimote-accel$i domain=accel$i grab persist=exit \
            --block abs:rz@accel$i abs:rx@accel$i \
            --map abs:ry:-59~..~-60@accel$i btn:select:1@wiitar$i \
            --map abs:ry:~-60..-59~@accel$i btn:select:0@wiitar$i \
        --output name="Wiitar w/ Tilt $i" @wiitar$i
done
